### ISSUE TITLE
Fix Resource re-rendering with BE requests

### ISSUE THREAD

**Issue by raresraf** [raresraf/metricsUI#4]

**Comment by raresraf** [comment]
https://github.com/raresraf/metricsUI/blob/3c4c1236018b73e25d4849b84efb92c353b791a1/src/context/ResourceContext.js#L48

**Comment by mihaipredoiu** [comment]
Use Context Consumer

**Comment by raresraf** [comment]
Maybe 👀

**Comment by raresraf** [comment]
https://github.com/raresraf/metricsUI/commit/3ea56fcf17293cd3b0b15502724dba3091a06df0
